export const SET_SELF_RATED_EXPERTISE = 'SET_SELF_RATED_EXPERTISE';
export const SET_ANNUAL_INCOME_RANGE = 'SET_ANNUAL_INCOME_RANGE';
export const SET_CREDIT_SCORE_RANGE = 'SET_CREDIT_SCORE_RANGE';

export const SET_RECOMMENDED_USER_TYPE = 'SET_RECOMMENDED_USER_TYPE';
export const SET_CHOSEN_USER_TYPE = 'SET_CHOSEN_USER_TYPE';
