export default {
  'Blue Cash EveryDay®': {
    bank: 'American Express',
    name: 'Blue Cash EveryDay®',
    cashback: 5,
    grocery: 5,
    gas: 2,
    travel: 0,
    dining: 0,
    building: 4,
    student: 2,
    balance_transfer: 2,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 650,
    annual_income_min: '10000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/blue-cash-everyday-credit-card/28009-10-0',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/blue-cash-everyday.png'
  },
  'Blue Cash Preferred® Card': {
    bank: 'American Express',
    name: 'Blue Cash Preferred® Card',
    cashback: 6,
    grocery: 10,
    gas: 3,
    travel: 0,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'yes',
    credit_min: 690,
    annual_income_min: '15000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/blue-cash-preferred-credit-card/25330-10-0?pmccode=796&intlink=US-Acq-Shop-Consumer-VAC-Prospect-Apply-BCP',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/blue-cash-preferred.png'
  },
  'Amex EveryDay®': {
    bank: 'American Express',
    name: 'Amex EveryDay®',
    cashback: 5,
    grocery: 2,
    gas: 2,
    travel: 0,
    dining: 0,
    building: 4,
    student: 2,
    balance_transfer: 2,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 650,
    annual_income_min: '10000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/amex-everyday-credit-card/36182-10-0?pmccode=937&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-AED',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/amex-everyday.png'
  },
  'Amex EveryDay® Preferred ': {
    bank: 'American Express',
    name: 'Amex EveryDay® Preferred ',
    cashback: 6,
    grocery: 5,
    gas: 2,
    travel: 0,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'yes',
    credit_min: 690,
    annual_income_min: '15000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/amex-everyday-preferred-credit-card/90001-10-0?pmccode=936&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-AEDP',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/amex-everyday-preferred.png'
  },
  'Cash Magnet® Card': {
    bank: 'American Express',
    name: 'Cash Magnet® Card',
    cashback: 6,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 1,
    student: 3,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 650,
    annual_income_min: '10000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/american-express-cash-magnet-card/36182-10-0?pmccode=1084&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-CashMagnet',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/cash-magnet.png'
  },
  'The Platinum Card® by American Express': {
    bank: 'American Express',
    name: 'The Platinum Card® by American Express',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 9,
    dining: 5,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 750,
    annual_income_min: '40000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/platinum-charge-card/36182-10-0?pmccode=137&intlink=US-Acq-Shop-Consumer-CardDetails-Platinum-CardMember-Apply-Platinum-Header',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/platinum-card.png'
  },
  'American Express® Gold Card': {
    bank: 'American Express',
    name: 'American Express® Gold Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 5,
    dining: 8,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25,000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/gold-card/36182-10-0?pmccode=784&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-GoldCard',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/gold-card.png'
  },
  'Blue Delta SkyMiles®': {
    bank: 'American Express',
    name: 'Blue Delta SkyMiles®',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 2,
    dining: 1,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 680,
    annual_income_min: '10000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/blue-delta-skymiles-credit-card/36182-10-0?pmccode=105&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-DeltaBlue',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/delta-blue.png'
  },
  'Gold Delta SkyMiles®': {
    bank: 'American Express',
    name: 'Gold Delta SkyMiles®',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 2,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 690,
    annual_income_min: '15000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/delta-gold-credit-card/36182-10-0?pmccode=113&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-DeltaGold',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/gold-delta-skymiles.png'
  },
  'Platinum Delta SkyMiles®': {
    bank: 'American Express',
    name: 'Platinum Delta SkyMiles®',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/platinum-delta-skymiles-credit-card/36182-10-0?pmccode=142&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-DeltaPlatinum',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/platinum-delta-skymiles.png'
  },
  'Delta Reserve® Credit Card': {
    bank: 'American Express',
    name: 'Delta Reserve® Credit Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 750,
    annual_income_min: '40000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/delta-reserve-credit-card/36182-10-0?pmccode=106&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-DeltaReserve',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/delta-reserve.png'
  },
  'Marriott Bonvoy Brilliant': {
    bank: 'American Express',
    name: 'Marriott Bonvoy Brilliant',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 1,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 750,
    annual_income_min: '40000',
    apply_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/marriott-bonvoy-brilliant-card.png',
    card_img_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/marriott-bonvoy-brilliant-card/36182-10-0?pmccode=1150&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-MarriottBonvoyBrilliant'
  },
  'American Express® Green Card': {
    bank: 'American Express',
    name: 'American Express® Green Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 1,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'yes',
    credit_min: 680,
    annual_income_min: '10000',
    apply_link:
      'https://www.americanexpress.com/us/credit-cards/card-application/apply/preferred-rewards-green-charge-card/36182-10-0?pmccode=145&intlink=US-Acq-Shop-Consumer-VAC-CardMember-Apply-Green',
    card_img_link:
      'https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/green-card.png'
  },
  Freedom: {
    bank: 'JPMorgan Chase',
    name: 'Freedom',
    cashback: 5,
    grocery: 2,
    gas: 1,
    travel: 0,
    dining: 0,
    building: 1,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 650,
    annual_income_min: '10000',
    apply_link:
      'https://applynow.chase.com/FlexAppWeb/renderApp.do?SPID=FW4L&CELL=61FY&PROMO=DF01',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/freedom_card.png'
  },
  'Freedom Unlimited': {
    bank: 'JPMorgan Chase',
    name: 'Freedom Unlimited',
    cashback: 6,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 2,
    student: 2,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 650,
    annual_income_min: '10000',
    apply_link:
      'https://applynow.chase.com/FlexAppWeb/renderApp.do?SPID=FY9N&CELL=61FY&PROMO=DF01',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/freedom_unlimited_card.png'
  },
  'Chase Sapphire Preferred': {
    bank: 'JPMorgan Chase',
    name: 'Chase Sapphire Preferred',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 8,
    dining: 4,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25,000',
    apply_link:
      'https://applynow.chase.com/FlexAppWeb/renderApp.do?SPID=FYQ8&CELL=61FY&PROMO=DF01',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/sapphire_preferred_card.png'
  },
  'Chase Sapphire Reserve': {
    bank: 'JPMorgan Chase',
    name: 'Chase Sapphire Reserve',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 9,
    dining: 4,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 750,
    annual_income_min: '40,000',
    apply_link:
      'https://applynow.chase.com/FlexAppWeb/renderApp.do?SPID=FXMT&CELL=61DS&PROMO=DF01',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/sapphire_reserve_card.png'
  },
  'Marriott Bonvoy Boundless™': {
    bank: 'JPMorgan Chase',
    name: 'Marriott Bonvoy Boundless™',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 2,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25,000',
    apply_link:
      'https://applynow.chase.com/FlexAppWeb/renderApp.do?SPID=FY2G&CELL=6TKV&PROMO=DF01',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/marriott_bonvoy_boundless_card.png'
  },
  'United Explorer Card': {
    bank: 'JPMorgan Chase',
    name: 'United Explorer Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 690,
    annual_income_min: '25,000',
    apply_link:
      'https://creditcards.chase.com/travel-credit-cards/united-explorer?iCELL=61FY',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/united_explorer_card.png'
  },
  'Chase Slate® credit card': {
    bank: 'JPMorgan Chase',
    name: 'Chase Slate® credit card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 1,
    student: 0,
    balance_transfer: 8,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 650,
    annual_income_min: '10000',
    apply_link:
      'https://creditcards.chase.com/balance-transfer-credit-cards/chase-slate?iCELL=61FY',
    card_img_link:
      'https://creditcards.chase.com/balance-transfer-credit-cards/chase-slate?iCELL=61FY'
  },
  'IHG® Rewards Club Premier Credit Card': {
    bank: 'JPMorgan Chase',
    name: 'IHG® Rewards Club Premier Credit Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link:
      'https://creditcards.chase.com/travel-credit-cards/ihg-rewards-club-premier?CELL=60LC',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/ihg_premier_card.png'
  },
  'The World of Hyatt Credit Card': {
    bank: 'JPMorgan Chase',
    name: 'The World of Hyatt Credit Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link:
      'https://creditcards.chase.com/travel-credit-cards/world-of-hyatt-credit-card?CELL=60LC',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/world_of_hyatt_card.png'
  },
  'Southwest Rapid Rewards® Priority Credit Card': {
    bank: 'JPMorgan Chase',
    name: 'Southwest Rapid Rewards® Priority Credit Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 2,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 700,
    annual_income_min: '15000',
    apply_link:
      'https://creditcards.chase.com/travel-credit-cards/southwest-priority?CELL=60LC',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/swa_priority_card.png'
  },
  'Southwest Rapid Rewards® Plus Credit Card': {
    bank: 'JPMorgan Chase',
    name: 'Southwest Rapid Rewards® Plus Credit Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 2,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 700,
    annual_income_min: '15000',
    apply_link:
      'https://creditcards.chase.com/travel-credit-cards/southwest-plus?CELL=60LC',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/swa_plus_card.png'
  },
  'Southwest Rapid Rewards® Premier Credit Card': {
    bank: 'JPMorgan Chase',
    name: 'Southwest Rapid Rewards® Premier Credit Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 3,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link:
      'https://creditcards.chase.com/travel-credit-cards/southwest-premier?CELL=60LC',
    card_img_link:
      'https://creditcards.chase.com/K-Marketplace/images/cardart/swa_premier_card.png'
  },
  'Discover it® Chrome': {
    bank: 'Discover',
    name: 'Discover it® Chrome',
    cashback: 5,
    grocery: 0,
    gas: 2,
    travel: 0,
    dining: 1,
    building: 2,
    student: 1,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 670,
    annual_income_min: '10000',
    apply_link:
      'https://www.discovercard.com/application/apply?srcCde=GEGP&iq_id=&aid=568217&pid=354162&sid=05431431&ef_id=&lfo_id=UXx0aO3F8xyJTNh0MvSyQWlBUklwCKVO0Xf7w80&SCMPGN=ACQ_LISTINGSITE_CONSUMER_CHROME_APPLY',
    card_img_link:
      'https://cdn.creditcards.com/shared/images/cards/336x211/discover-it-chrome-012518.png'
  },
  'Discover Secured': {
    bank: 'Discover',
    name: 'Discover Secured',
    cashback: 1,
    grocery: 0,
    gas: 2,
    travel: 0,
    dining: 2,
    building: 5,
    student: 5,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 0,
    annual_income_min: '0',
    apply_link:
      'https://www.discovercard.com/application/displayLanding?pageFileId=double-listingsite-secured&sc=GEGX&cmpgnid=ls-dca-ir-secured-GEGX-434&irgwc=1&gclid=UXx0aO3F8xyJTNh0MvSyQWlBUklwCcz20Xf7w80&sid=05431431&pid=354162&aid=568217',
    card_img_link:
      'https://cdn.creditcards.com/shared/images/cards/336x211/discover-it-secured-card-012518.png'
  },
  'Discover Miles': {
    bank: 'Discover',
    name: 'Discover Miles',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 4,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 670,
    annual_income_min: '15000',
    apply_link:
      'https://www.discovercard.com/application/displayLanding?pageFileId=listingsite-miles&sc=GEGY&cmpgnid=ls-dca-ir-consumer-miles-GEGY-dtop-434&irgwc=1&gclid=UV6UAQ3F8xyJW-M0MSU5wRc5UklwCKyX0Xf7w80&sid=05431431&pid=354162&aid=568217',
    card_img_link:
      'https://cdn.creditcards.com/shared/images/cards/336x211/discover-it-miles-012518.png'
  },
  'Discover it® Cash Back': {
    bank: 'Discover',
    name: 'Discover it® Cash Back',
    cashback: 6,
    grocery: 1,
    gas: 0,
    travel: 0,
    dining: 2,
    building: 1,
    student: 1,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 670,
    annual_income_min: '10000',
    apply_link:
      'https://www.discovercard.com/application/displayLanding?pageFileId=double-listingsite&sc=GEGN&cmpgnid=ls-dca-ir-consumer-it-GEGN-dtop-434&irgwc=1&gclid=UXx0aO3F8xyJTNh0MvSyQWlBUklwCKyX0Xf7w80&sid=05431431&pid=354162&aid=568217',
    card_img_link:
      'https://cdn.creditcards.com/shared/images/cards/336x211/discover-it-cashback-match-012518.png'
  },
  'Discover it® Student Cash Back': {
    bank: 'Discover',
    name: 'Discover it® Student Cash Back',
    cashback: 6,
    grocery: 0,
    gas: 1,
    travel: 0,
    dining: 2,
    building: 1,
    student: 8,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 0,
    annual_income_min: '0',
    apply_link:
      'https://www.discovercard.com/application/displayLanding?pageFileId=double-listingsite_student&sc=RJUK&cmpgnid=ls-dca-ir-student-it-RJUK-dtop-434&irgwc=1&gclid=UXx0aO3F8xyJTNh0MvSyQWlBUklwCc2e0Xf7w80&sid=05431431&pid=354162&aid=568217',
    card_img_link:
      'https://cdn.creditcards.com/shared/images/cards/336x211/discover-it-for-students-012518.png'
  },
  Venture: {
    bank: 'Capital One',
    name: 'Venture',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 6,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link: 'https://applynow.capitalone.com/?productId=5800',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/venture-card-art.png'
  },
  VentureOne: {
    bank: 'Capital One',
    name: 'VentureOne',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 4,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link: 'https://applynow.capitalone.com/?productId=5713',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/ventureone-card-art.png'
  },
  Quicksilver: {
    bank: 'Capital One',
    name: 'Quicksilver',
    cashback: 6,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 1,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 700,
    annual_income_min: '15000',
    apply_link: 'https://applynow.capitalone.com/?productId=5498',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/quicksilver-card-art.png'
  },
  Savor: {
    bank: 'Capital One',
    name: 'Savor',
    cashback: 5,
    grocery: 2,
    gas: 0,
    travel: 0,
    dining: 6,
    building: 0,
    student: 1,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 690,
    annual_income_min: '15000',
    apply_link: 'https://applynow.capitalone.com/?productId=5522',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/savor-card-art.png'
  },
  QuicksilverOne: {
    bank: 'Capital One',
    name: 'QuicksilverOne',
    cashback: 6,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 0,
    student: 1,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'yes',
    credit_min: 690,
    annual_income_min: '15000',
    apply_link: 'https://applynow.capitalone.com/?productId=5890',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/quicksilverone-card-art.png'
  },
  SavorOne: {
    bank: 'Capital One',
    name: 'SavorOne',
    cashback: 5,
    grocery: 2,
    gas: 0,
    travel: 0,
    dining: 4,
    building: 0,
    student: 1,
    balance_transfer: 2,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 690,
    annual_income_min: '15000',
    apply_link: 'https://applynow.capitalone.com/?productId=5513',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/savorone-card-art.png'
  },
  'CapitalOne Platinum': {
    bank: 'Capital One',
    name: 'CapitalOne Platinum',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 5,
    student: 3,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 0,
    annual_income_min: '5000',
    apply_link: 'https://applynow.capitalone.com/?productId=5891',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/platinum-card-art.png'
  },
  'CapitalOne Journey® Student Rewards': {
    bank: 'Capital One',
    name: 'CapitalOne Journey® Student Rewards',
    cashback: 4,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 1,
    student: 7,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 0,
    annual_income_min: '0',
    apply_link: 'https://applynow.capitalone.com/?productId=5892',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/journey-card-art.png'
  },
  'CapitalOne Secured Mastercard®': {
    bank: 'Capital One',
    name: 'CapitalOne Secured Mastercard®',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 0,
    building: 8,
    student: 5,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 0,
    annual_income_min: '0',
    apply_link: 'https://applynow.capitalone.com/?productId=5549',
    card_img_link:
      'https://www.capitalone.com/assets/credit-cards/img/platinum-card-art.png'
  },
  'Citi® Double Cash Card': {
    bank: 'Citi',
    name: 'Citi® Double Cash Card',
    cashback: 7,
    grocery: 1,
    gas: 0,
    travel: 0,
    dining: 1,
    building: 1,
    student: 1,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 670,
    annual_income_min: '10000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-double-cash-credit-card&category=view-all-credit-cards&afc=1C2&intc=7~7~67~1~MCT~1~citi-double-cash-credit-card',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/citi-double-cash-credit-card.jpg'
  },
  'Citi Simplicity® Card': {
    bank: 'Citi',
    name: 'Citi Simplicity® Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 0,
    dining: 1,
    building: 1,
    student: 1,
    balance_transfer: 3,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 650,
    annual_income_min: '10000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-simplicity-credit-card&category=view-all-credit-cards&afc=1C2&intc=7~7~67~1~MCT~1~citi-simplicity-credit-card',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/citi-simplicity-credit-card.jpg'
  },
  'Citi Rewards+ Card': {
    bank: 'Citi',
    name: 'Citi Rewards+ Card',
    cashback: 5,
    grocery: 0,
    gas: 2,
    travel: 0,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 2,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 670,
    annual_income_min: '10000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-rewards-plus-credit-card&category=view-all-credit-cards&afc=1C2&intc=7~7~67~1~MCT~1~citi-rewards-plus-credit-card',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/citi-rewards-plus-credit-card.jpg'
  },
  'AAdvantage MileUp℠ Card': {
    bank: 'Citi',
    name: 'AAdvantage MileUp℠ Card',
    cashback: 0,
    grocery: 0,
    gas: 0,
    travel: 2,
    dining: 0,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'small',
    annual_fee: 'no',
    credit_min: 670,
    annual_income_min: '10000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=aadvantage-mile-up-credit-card&category=travel-reward-credit-cards&afc=1C1&intc=7~7~67~1~MCT~1~CMSDefaultOffer',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/aadvantage-mile-up-credit-card.jpg'
  },
  'AAdvantage® Platinum Select® World Elite™ Mastercard®': {
    bank: 'Citi',
    name: 'AAdvantage® Platinum Select® World Elite™ Mastercard®',
    cashback: 0,
    grocery: 0,
    gas: 1,
    travel: 2,
    dining: 2,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-aadvantage-platinum-elite-credit-card&category=travel-reward-credit-cards&afc=1C1&intc=7~7~67~1~MCT~1~CMSDefaultOffer',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/citi-aadvantage-platinum-elite-credit-card.jpg'
  },
  'AAdvantage® Executive World Elite™ Mastercard®': {
    bank: 'Citi',
    name: 'AAdvantage® Executive World Elite™ Mastercard®',
    cashback: 0,
    grocery: 0,
    gas: 1,
    travel: 3,
    dining: 2,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 750,
    annual_income_min: '40000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-aadvantage-executive-credit-card&category=travel-reward-credit-cards&afc=1C1&intc=7~7~67~1~MCT~1~citi-aadvantage-executive-credit-card',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/citi-aadvantage-executive-credit-card.jpg'
  },
  'Citi Premier Card': {
    bank: 'Citi',
    name: 'Citi Premier Card',
    cashback: 0,
    grocery: 0,
    gas: 3,
    travel: 6,
    dining: 4,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 720,
    annual_income_min: '25000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-premier-credit-card&category=travel-reward-credit-cards&afc=1C1&intc=7~7~67~1~MCT~1~citi-premier-credit-card',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/citi-thankyou-premier-credit-card.jpg'
  },
  'Citi Prestige® Credit Card': {
    bank: 'Citi',
    name: 'Citi Prestige® Credit Card',
    cashback: 0,
    grocery: 0,
    gas: 4,
    travel: 7,
    dining: 5,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'large',
    annual_fee: 'yes',
    credit_min: 750,
    annual_income_min: '40000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-prestige-card&category=travel-reward-credit-cards&afc=1C1&intc=7~7~67~1~MCT~1~CMSDefaultOffer',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/citi-prestige-card.jpg'
  },
  'Costco Anywhere Visa®': {
    bank: 'Citi',
    name: 'Costco Anywhere Visa®',
    cashback: 3,
    grocery: 3,
    gas: 4,
    travel: 0,
    dining: 3,
    building: 0,
    student: 0,
    balance_transfer: 0,
    bonus_purchase: 'no',
    annual_fee: 'no',
    credit_min: 670,
    annual_income_min: '10000',
    apply_link:
      'https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=Citi-costco-anywhere-visa-credit-card&category=savings-and-cash-back-credit-cards&afc=1A8&intc=7~7~67~1~MCT~1~CMSDefaultOffer',
    card_img_link:
      'https://www.citi.com/CRD/images/card_no_reflection/Citi-costco-anywhere-visa-credit-card.jpg'
  }
};
